"""Game-model-orm

Revision ID: 06dade4dd9ef
Revises: c86437618e1d
Create Date: 2025-07-28 15:48:23.467650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dade4dd9ef'
down_revision: Union[str, Sequence[str], None] = 'c86437618e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('shortDescription', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('achievements', sa.Column('gameId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'achievements', 'games', ['gameId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'gameId')
    op.drop_table('games')
    # ### end Alembic commands ###
