"""emojis

Revision ID: 203d30acc0e1
Revises: 34a8d8195c0a
Create Date: 2025-07-27 17:45:13.628602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203d30acc0e1'
down_revision: Union[str, Sequence[str], None] = '34a8d8195c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('emoji', sa.String(length=50), nullable=False))
    op.add_column('levels', sa.Column('emoji', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'emoji')
    op.drop_column('achievements', 'emoji')
    # ### end Alembic commands ###
