"""initial-revision

Revision ID: 34a8d8195c0a
Revises: 
Create Date: 2025-07-27 14:11:49.869300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a8d8195c0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conditionKey', sa.String(length=100), nullable=False),
    sa.Column('conditionValue', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('title', sa.Enum('beginner', 'novice', 'learner', 'junior', 'intermediate', 'skilled', 'advanced', 'level_8proficient', 'expert', 'master', name='level_title'), nullable=False),
    sa.Column('requiredScore', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegramId', sa.BigInteger(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('levelId', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['levelId'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatId'),
    sa.UniqueConstraint('telegramId')
    )
    op.create_table('user_stats',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('totalScore', sa.Integer(), nullable=False),
    sa.Column('learnMode', sa.Integer(), nullable=False),
    sa.Column('creativeMode', sa.Integer(), nullable=False),
    sa.Column('codeMode', sa.Integer(), nullable=False),
    sa.Column('antiPromptMode', sa.Integer(), nullable=False),
    sa.Column('promptPuzzlesMode', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_achievements')
    op.drop_table('user_stats')
    op.drop_table('users')
    op.drop_table('levels')
    op.drop_table('achievements')
    # ### end Alembic commands ###
