"""UserAchievement_to_orm

Revision ID: 6e2fafa4f194
Revises: bd6513301a6b
Create Date: 2025-07-28 14:15:50.840374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2fafa4f194'
down_revision: Union[str, Sequence[str], None] = 'bd6513301a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_achievements')
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_achievements',
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achievementId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['achievementId'], ['achievements.id'], name=op.f('users_achievements_achievementId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('users_achievements_userId_fkey'), ondelete='CASCADE')
    )
    op.drop_table('user_achievements')
    # ### end Alembic commands ###
