"""Game-mode

Revision ID: 7f4a05d75e20
Revises: 06dade4dd9ef
Create Date: 2025-07-28 19:01:52.970726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4a05d75e20'
down_revision: Union[str, Sequence[str], None] = '06dade4dd9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mode', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'mode')
    # ### end Alembic commands ###
