"""update-foreign-keys

Revision ID: 99b907c00b59
Revises: 9d9891ec484f
Create Date: 2025-07-28 13:19:18.978102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b907c00b59'
down_revision: Union[str, Sequence[str], None] = '9d9891ec484f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_stats_userId_fkey'), 'user_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_achievements_achievement_id_fkey'), 'users_achievements', type_='foreignkey')
    op.drop_constraint(op.f('users_achievements_user_id_fkey'), 'users_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'users_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_achievements', type_='foreignkey')
    op.drop_constraint(None, 'users_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('users_achievements_user_id_fkey'), 'users_achievements', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('users_achievements_achievement_id_fkey'), 'users_achievements', 'achievements', ['achievement_id'], ['id'])
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('user_stats_userId_fkey'), 'user_stats', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
