"""move-levelId-to-UserStats

Revision ID: 9a2db06421ce
Revises: 7f4a05d75e20
Create Date: 2025-07-29 15:45:05.282197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2db06421ce'
down_revision: Union[str, Sequence[str], None] = '7f4a05d75e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('levelId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_stats', 'levels', ['levelId'], ['id'])
    op.drop_constraint(op.f('users_levelId_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'levelId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('levelId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_levelId_fkey'), 'users', 'levels', ['levelId'], ['id'])
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.drop_column('user_stats', 'levelId')
    # ### end Alembic commands ###
