"""totalGamesPlayed

Revision ID: 9d9891ec484f
Revises: f485ccd0fe59
Create Date: 2025-07-28 02:07:34.086026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9891ec484f'
down_revision: Union[str, Sequence[str], None] = 'f485ccd0fe59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('totalGamesPlayed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'totalGamesPlayed')
    # ### end Alembic commands ###
