"""update_user_achievement

Revision ID: bd6513301a6b
Revises: 99b907c00b59
Create Date: 2025-07-28 13:38:15.628230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6513301a6b'
down_revision: Union[str, Sequence[str], None] = '99b907c00b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_achievements', sa.Column('userId', sa.Integer(), nullable=False))
    op.add_column('users_achievements', sa.Column('achievementId', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_achievements_achievement_id_fkey'), 'users_achievements', type_='foreignkey')
    op.drop_constraint(op.f('users_achievements_user_id_fkey'), 'users_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'users_achievements', 'achievements', ['achievementId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_achievements', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_column('users_achievements', 'achievement_id')
    op.drop_column('users_achievements', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_achievements', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users_achievements', sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_achievements', type_='foreignkey')
    op.drop_constraint(None, 'users_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('users_achievements_user_id_fkey'), 'users_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('users_achievements_achievement_id_fkey'), 'users_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users_achievements', 'achievementId')
    op.drop_column('users_achievements', 'userId')
    # ### end Alembic commands ###
