"""UserAchievement-fix-column-names

Revision ID: c86437618e1d
Revises: 6e2fafa4f194
Create Date: 2025-07-28 14:23:22.949080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86437618e1d'
down_revision: Union[str, Sequence[str], None] = '6e2fafa4f194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_achievements', sa.Column('userId', sa.Integer(), nullable=False))
    op.add_column('user_achievements', sa.Column('achievementId', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_achievements_achievement_id_fkey'), 'user_achievements', type_='foreignkey')
    op.drop_constraint(op.f('user_achievements_user_id_fkey'), 'user_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'user_achievements', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'user_achievements', 'achievements', ['achievementId'], ['id'])
    op.drop_column('user_achievements', 'achievement_id')
    op.drop_column('user_achievements', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_achievements', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_achievements', sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.drop_constraint(None, 'user_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('user_achievements_user_id_fkey'), 'user_achievements', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_achievements_achievement_id_fkey'), 'user_achievements', 'achievements', ['achievement_id'], ['id'])
    op.drop_column('user_achievements', 'achievementId')
    op.drop_column('user_achievements', 'userId')
    # ### end Alembic commands ###
