"""puzzleMode-field-UserStats

Revision ID: e6bfc731b630
Revises: 9a2db06421ce
Create Date: 2025-07-29 18:46:12.205688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bfc731b630'
down_revision: Union[str, Sequence[str], None] = '9a2db06421ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('puzzleMode', sa.Integer(), nullable=False))
    op.drop_column('user_stats', 'promptPuzzlesMode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('promptPuzzlesMode', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_stats', 'puzzleMode')
    # ### end Alembic commands ###
