"""level_title

Revision ID: f485ccd0fe59
Revises: 203d30acc0e1
Create Date: 2025-07-27 21:15:58.736741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f485ccd0fe59'
down_revision: Union[str, Sequence[str], None] = '203d30acc0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'title',
               existing_type=postgresql.ENUM('beginner', 'novice', 'learner', 'junior', 'intermediate', 'skilled', 'advanced', 'level_8proficient', 'expert', 'master', name='level_title'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'title',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('beginner', 'novice', 'learner', 'junior', 'intermediate', 'skilled', 'advanced', 'level_8proficient', 'expert', 'master', name='level_title'),
               existing_nullable=False)
    # ### end Alembic commands ###
